id: P007088
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG21600
  title: འཕྲོད་བསྟེན་སྐོར་གི་སྟབས་བདེའི་ཤེས་བྱ།
  author: ''
  volumes:
    362091ad6e984ee088b9bb21dd83d1c7:
      image_group_id: I1KG21727
      title: ''
      volume_number: 1
      total_pages: 30
ebook_metadata:
  title: འཕྲོད་བསྟེན་སྐོར་གི་སྟབས་བདེའི་ཤེས་བྱ།
  author: ''
  sku: P007088
  cover: cover.jpg
  layers:
  - pagination
