id: I84D698C9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T23:14:41+00:00'
last_modified: '2022-06-09T04:44:56.480436+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21600
  title: འཕྲོད་བསྟེན་སྐོར་གི་སྟབས་བདེའི་ཤེས་བྱ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3567':
      image_group_id: I1KG21727
      title: Volume 1 of 'phrod bsten skor gi stabs bde'i shes bya/
      total_pages: 30
      order: 1
      base_file: 3567.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
